import { describe, expect, it } from "vitest";
import type { ParsedCodexLine } from "../../../../lib/codex-conversation-schema/parseCodexJsonl";
import { extractFirstUserMessage } from "./isValidFirstMessage";

const createUserMessageLine = (text: string): ParsedCodexLine => {
  return {
    timestamp: "2026-02-07T00:00:00.000Z",
    type: "response_item",
    payload: {
      type: "message",
      role: "user",
      content: [{ type: "input_text", text }],
    },
  };
};

const firstUserFromConversations = (conversations: ParsedCodexLine[]) => {
  for (const conversation of conversations) {
    const firstUser = extractFirstUserMessage(conversation);
    if (firstUser !== undefined) {
      return firstUser;
    }
  }
  return null;
};

describe("extractFirstUserMessage", () => {
  it("skips local-command caveat and uses the next user message", () => {
    const caveat =
      "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
    const userText = "/create-draft-pr please ignore";
    const stdout =
      "<local-command-stdout>output that should not be first</local-command-stdout>";

    const result = firstUserFromConversations([
      createUserMessageLine(caveat),
      createUserMessageLine(userText),
      createUserMessageLine(stdout),
    ]);

    expect(result?.kind).toBe("text");
    if (result?.kind === "text") {
      expect(result.content).toBe(userText);
    }
  });

  it("returns local-command stdout when it is the first non-caveat message", () => {
    const caveat =
      "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
    const stdout =
      "<local-command-stdout>hello <tag>world</tag></local-command-stdout>";

    const result = firstUserFromConversations([
      createUserMessageLine(caveat),
      createUserMessageLine(stdout),
    ]);

    expect(result?.kind).toBe("local-command");
    if (result?.kind === "local-command") {
      expect(result.stdout).toBe("hello <tag>world</tag>");
    }
  });
});
